# Generated by Django 4.2 on 2023-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersound',
            name='name',
            field=models.TextField(default='None'),
        ),
    ]
